Add docker
mynameisSergey/java-shareit pull request #11
Opened 2023-06-30 01:20 UTC by mynameisSergey

2023-06-30 21:13 UTC, Fleaman777 requested changes

2023-06-30 21:13 UTC, Fleaman777 commented on docker-compose.yml
> +    image: postgres:13.7-alpine
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,
то же относится и к Dockerfile

2023-06-30 21:13 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
можно не указывать значение для name параметра, если оно совпадает с названием аргумента метода
меньше кода, меньше отвлекающих вещей

2023-06-30 21:13 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public ErrorResponse handleException(final Exception e) {
а есть ли смысл разделть хэндлеры на 2 вида эксепшенов ?
почему бы не оставить 1 хэндлер

2023-06-30 21:13 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/exceptions/ErrorResponse.java
> +    public String getStackTrace() {
этот код можно сделать через аннотации, 
так будет единообразие в объявлении модельных классов

2023-06-30 21:13 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String REQUEST_HEADER_SHARER_USER_ID = "X-Sharer-User-Id";
по джава код стайлу, статическая переменная должна идти перед обычной

2023-06-30 21:13 UTC, Fleaman777 commented on server/src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "status")
если названия параметра name совпадает с названием поля, то можно не указывать аннотацию, 
что в целом хорошо, т.к. будет меньше кода, меньше отвлекающих факторов, 
к тому же, если все таки где-то название колонки не будет совпадать с названием поля, то мы это точно не пропустим, т.к. у нас аннотация Column будет висеть только в тех местах, где это действительно необходимо

2023-06-30 21:13 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
здесь можно было бы добавить перменную SPRING_DATASOURCE_URL, что бы явно было ее видно

2023-07-01 13:04 UTC, mynameisSergey commented on docker-compose.yml
> +    image: postgres:13.7-alpine
) спасибо

2023-07-01 13:11 UTC, mynameisSergey commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
исправил

2023-07-01 13:16 UTC, mynameisSergey commented on gateway/src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public ErrorResponse handleException(final Exception e) {
если ты не против, пока я оставил бы так. для себя, для простоты понимания для чего какой эксепшен нужен. Спасибо за совет. обязательно учту его в дальнейшем

2023-07-01 13:17 UTC, mynameisSergey commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String REQUEST_HEADER_SHARER_USER_ID = "X-Sharer-User-Id";
исправил

2023-07-01 13:19 UTC, mynameisSergey commented on server/src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "status")
исправил

2023-07-01 13:27 UTC, mynameisSergey commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
спасибо за совет. я просто старался придерживаться теории))) чистый код пока в перспективе))

2023-07-01 13:33 UTC, mynameisSergey commented on gateway/src/main/java/ru/practicum/shareit/exceptions/ErrorResponse.java
> +    public String getStackTrace() {
исправил

2023-07-02 18:08 UTC, Fleaman777 approved these changes

2025-02-20 12:32 UTC, closed without merging