Add controllers
mynameisSergey/java-shareit pull request #2
Opened 2023-05-22 19:49 UTC by mynameisSergey

2023-05-23 16:10 UTC, Fleaman777 requested changes

2023-05-23 16:10 UTC, Fleaman777 commented on pom.xml
> +			<version>${commons-lang3.version}</version>
хорошая библиотека

2023-05-23 16:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        }
проверку наличия айди можно было бы вынести в отдельный метод

2023-05-23 16:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String XSHARERUSERID = "X-Sharer-User-Id";
по джава код стайлу, статичное поле идет до обычного

2023-05-23 16:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemService(ItemStorage itemStorage, UserStorage userStorage) {
если использовать ломбок аннотацию @RequiredArgsConstructor, то можно будет явно не объявлять конструктор и не вешать на него @Autowire аннотацию

2023-05-23 16:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +    private final HashMap<Integer, User> users = new HashMap();
если тип сделать более широким Map, 
то полиморфизм будет работать лучше

2023-05-23 16:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        }
проверку наличия юзера можно вынести в отдельный метод, что бы не дублироват эту логику в разных методах

2023-05-23 20:26 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String XSHARERUSERID = "X-Sharer-User-Id";
Исправил

2023-05-23 20:28 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemService(ItemStorage itemStorage, UserStorage userStorage) {
Исправил

2023-05-23 20:29 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +    private final HashMap<Integer, User> users = new HashMap();
исправил

2023-05-23 20:45 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        }
исправил

2023-05-23 20:48 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        }
исправил

2023-05-24 16:05 UTC, Fleaman777 approved these changes

2023-06-05 00:52 UTC, merged