Добрый день! спринт 14
mynameisSergey/java-shareit pull request #7
Opened 2023-06-05 09:19 UTC by mynameisSergey

2023-06-05 19:47 UTC, Fleaman777 requested changes

2023-06-05 19:47 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                    @RequestParam(name = "approved") Boolean approved) {
можно не указывать значение для name параметра, если оно совпадает с названием аргумента метода

2023-06-05 19:47 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingController(BookingService bookingService) {
здесь тоже можно было бы применить @RequiredArgsConstructor, что бы унифицировать этот момент во всем приложении

2023-06-05 19:47 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.isPresent()) {
это условие можно было бы инвертировать и соответственно выбрасовать             throw new ObjectNotFoundException("Бронирование не найдено") что бы не оборачивать последующих код в блок { }

2023-06-05 19:47 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.isPresent()) {
здесь аналагично, 
тоже можно инвертировать условие

2023-06-05 21:43 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                    @RequestParam(name = "approved") Boolean approved) {
исправил

2023-06-05 21:53 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.isPresent()) {
исправил

2023-06-05 21:55 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.isPresent()) {
исправил

2023-06-05 21:58 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingController(BookingService bookingService) {
исправил

2023-06-05 22:18 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.isPresent()) {
здесь, если ты не против, я оставил бы как есть
все остальное исправил. спасибо за ревью)

2023-06-06 18:47 UTC, Fleaman777 approved these changes

2023-06-24 12:32 UTC, merged