Add item requests
mynameisSergey/java-shareit pull request #9
Opened 2023-06-25 13:20 UTC by mynameisSergey

2023-06-26 18:00 UTC, Fleaman777 requested changes

2023-06-26 18:00 UTC, Fleaman777 commented on pom.xml
> +		</dependency>
можно не включать эту зависимость, т.к. spring-data-jpa уже содержит ее в себе ее

2023-06-26 18:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "status")
если названия параметра name совпадает с названием поля, то можно не указывать аннотацию, 
что в целом хорошо, т.к. будет меньше кода, меньше отвлекающих факторов, 
к тому же, если все таки где-то название колонки не будет совпадать с названием поля, то мы это точно не пропустим, т.к. у нас аннотация Column будет висеть только в тех местах, где это действительно необходимо

2023-06-26 18:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDtoOut create(@RequestHeader("X-Sharer-User-Id") Long userId,
X-Sharer-User-Id можно было бы вынести в константу

2023-06-26 18:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                      @RequestParam(value = "size", defaultValue = "10") @Min(1) Integer size) {
можно не указывать значение для name параметра, если оно совпадает с названием аргумента метода
меньше кода, меньше отвлекающих вещей

2023-06-26 18:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDtoOut add(Long userId, BookingDto bookingDto) {
под add может много чего добавляться, лучше немного уточнить название

аналагичино с update

2023-06-26 18:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDtoOut> getAllOwner(Long ownerId, String state, Integer from, Integer size) {
getAllOwners

2023-06-26 18:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +package ru.practicum.shareit.booking;
вижу что перенес все классы в один пакет, но на самом деле, хорошо было бы все оставить по соответствующим подпакетам, что бы не было каши из классов
т.к. их количество будет только расти, что приведет к сложности восприятия структуры

аналагично с другими сущностями

2023-06-26 18:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/User.java
> +package ru.practicum.shareit.user;
продолжая тему переноса всех классов в один пакет, 
этот рефакторинг добавляет сложности проверки нового кода, т.к. новый функционал затерялся где-то внутри перенесенных классов, 

как результат, я могу пропустить важные изменения или наоборот, еще раз пройтись по старым, что затянет исправние

лучше, если хочется сделать рефакторинг, делать это отдельной задачей, так проще будет с ним работать

2023-06-26 18:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case 1:
есть такой антипаттерн, магические цыфры, 
когда только программист, который писал код, понимает, что именно это за значение и почему именно такое, 

в данном случае и переменная имеет слишком общее название, и само значение непонятно почему именно такое, 

как минимум можно добавить небольшой комментарий, 
а еще лучше иметь человекочитаемый формат, т.е. что-то типа енам класса

2023-06-26 18:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", user.getId())
X-Sharer-User-Id в тестах так же можно было бы вынести в константу

2023-06-26 18:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void update_whenBookingIsValid_thenReturnStatusIsOk() {
хорошие нащвания тест методов, говорят о том, что тестируется и какой результат

2023-06-26 18:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        Integer size = 10;
from size так же можно вынести в константы

2023-06-26 18:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    void getLastBooking() {
название тест метода должно отличаться от названия основного класса, что бы было проще искать по всему коду

аналогично в других метсах

2023-06-26 18:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        if (bookingOptional.isPresent()) {
в тесте не должно быть условия if-else, т.к. в тесте четко определено, что должно быть выполнено и проверено

2023-06-26 18:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIT.java
> +public class BookingServiceIT {
BookingServiceTest

2023-06-26 18:00 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +    }
некоторые комментарии относятся не только к одному тестовому классу, а в целом, применимы ко мнонигим
посмотри где их еще можно было бы применить и поправить

2023-06-26 18:06 UTC, mynameisSergey commented on pom.xml
> +		</dependency>
исправил

2023-06-26 18:08 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "status")
исправил

2023-06-26 18:19 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingDtoOut create(@RequestHeader("X-Sharer-User-Id") Long userId,
исправил

2023-06-26 18:21 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                      @RequestParam(value = "size", defaultValue = "10") @Min(1) Integer size) {
исправил

2023-06-26 18:25 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDtoOut add(Long userId, BookingDto bookingDto) {
Спасибо за замечание))) если ты не против, пока я оставил бы без изменения, пока не появился второй аналогичный метод add))

2023-06-26 18:28 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDtoOut> getAllOwner(Long ownerId, String state, Integer from, Integer size) {
исправил

2023-06-26 18:29 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +package ru.practicum.shareit.booking;
если возможно, этот вариант я пока оставил. по пакетам я уже привык работать. теперь обкатываю второй-без них. мне меньше нравится, но просто хочу испробовать разные варианты. на след ТЗ раскидаю по папкам))

2023-06-26 18:31 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/user/User.java
> +package ru.practicum.shareit.user;
спасибо за замечание. обязательно приму к сведению. это только 2 ТЗ, где я работаю без отдельных пакетов. обязательно исправлю в след тз. согласен с тобой.

2023-06-26 18:37 UTC, mynameisSergey commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case 1:
исправил

2023-06-26 18:41 UTC, mynameisSergey commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", user.getId())
исправил

2023-06-26 18:41 UTC, mynameisSergey commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void update_whenBookingIsValid_thenReturnStatusIsOk() {
спасибо)

2023-06-26 18:47 UTC, mynameisSergey commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        Integer size = 10;
исправил

2023-06-26 18:50 UTC, mynameisSergey commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    void getLastBooking() {
исправил

2023-06-26 18:58 UTC, mynameisSergey commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        if (bookingOptional.isPresent()) {
исправил

2023-06-26 18:59 UTC, mynameisSergey commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIT.java
> +public class BookingServiceIT {
исправил

2023-06-26 19:00 UTC, mynameisSergey commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +    }
спасибо тебе за обширное ревью, теперь мой код стал чище))

2023-06-27 19:33 UTC, Fleaman777 approved these changes

2023-06-27 19:33 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>      @PostMapping
тут если что пропуск строки должен быть )

2023-06-27 19:33 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    final String SHARER = "X-Sharer-User-Id";
я бы назвад USER_HEADER и кратко, и понятно)

2023-06-30 00:10 UTC, closed without merging